# 
# Workshop SQL 2022
#
# Authors: 
#   Nuno Antunes <nmsa@dei.uc.pt>
#   José Flora <jeflora@dei.uc.pt>
#   University of Coimbra


from python:3.10-alpine

RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev postgresql-client

run pip install psycopg2-binary


CMD ["sh"]


